add icon build
QwantResearch/map-style-builder pull request #13
Opened 2018-04-26 08:51 UTC by Julien-laville

2018-04-27 09:32 UTC, nlehuby commented
Here are a few tests to add:
* :x:  is there at least a layer in the style named `poi-level-*` ?
* :x: is there a `icons.yml` file in the directory ?
* for each elem in the yml file:
   * :warning:  is the color listed in the file?
   * :warning: is the icon listed in the file ?
   * :x:  is the icon present in the icon directory ?

2018-04-27 10:10 UTC, nlehuby commented on task/build_cli.js
> +  })
the `icons` arg is also needed

2018-04-27 12:40 UTC, nlehuby commented on task/icons/index.js
> +    iconsCases.push('default')
For now, the default icon should be `star-stroked-11`

2018-04-27 15:55 UTC, Julien-laville commented on task/build_cli.js
> +  })
done (je crois)

2018-04-30 14:48 UTC, nlehuby requested changes
:crying_cat_face:

2018-04-30 14:48 UTC, nlehuby commented on test/index.js
> +const i18nTest = require('./i18n')
this one does not exist for now :cry:

2018-04-30 14:48 UTC, nlehuby commented on test/index.js
> +let args = require('./../lib/style_args').argv;
this one does not exist either :sob:

2018-04-30 14:48 UTC, nlehuby commented on task/build_cli.js
> +let args = require('./../lib/style_args').argv;
this one does not exist either :disappointed:

2018-04-30 15:23 UTC, nlehuby approved these changes
:+1:

2018-04-30 16:13 UTC, amatissart approved these changes

2018-04-30 16:13 UTC, merged