Qmaps 153
QwantResearch/map-style-builder pull request #8
Opened 2018-01-09 17:10 UTC by Julien-laville

2018-01-12 14:55 UTC, antoine-de commented on task/build_cli.js
> +outPath = path.join(buildDir,'built-style.json');
you need to change the options too

2018-01-12 15:17 UTC, nlehuby requested changes

2018-01-12 15:17 UTC, nlehuby commented on package.json
> +    "build_all": "node task/build_cli.js"
You need to update the readme.
`npm run build_all -- PATH/TO/YOUR/MAPSTYLE/FOLDER PATH/TO/YOUR/CONF` does not work anymore
`npm run build_all -- --style_dir PATH/TO/YOUR/MAPSTYLE/FOLDER --conf PATH/TO/YOUR/CONF` is ok

2018-01-12 15:17 UTC, nlehuby commented on lib/build.js
> +      let jsonPath = `${options.outPath}${pixelRatioPath}.json`
The sprite json and png files are not generated in the outPath (missing a `/`)

2018-01-12 15:17 UTC, nlehuby commented on task/deploy.sh
> -node task/deploy.js
You can remove the deploy.js file too. We don't use it.

2018-01-12 15:17 UTC, nlehuby commented on lib/build.js
> +      style: style,
You need to parse the style as JSON before trying to transform it.

2018-01-12 15:17 UTC, nlehuby commented on lib/build.js
> +  return JSON.stringify(style)
You already stringify it in the `build_cli.js` file.

2018-01-12 15:17 UTC, nlehuby commented on lib/build.js
> +  if(options.ouput === 'dev') {
`options.output` is not set in `build_cli.js`

2018-01-15 11:02 UTC, nlehuby commented on lib/build.js
> +  if(options.ouput === 'production') {
You need to change `ouput` to `output` ;)

2018-01-15 11:07 UTC, nlehuby commented on task/build_cli.js
> +  conf : jsonconf,
`options.conf` is defined here, whereas `options.config` is expected in `build_cli`

2018-01-15 15:16 UTC, nlehuby approved these changes

2018-01-15 15:20 UTC, merged